---
title: Initial Configuration
description: Performs the preliminary configuration
actions:
  - !writeStatus: {status: 'Setting the environment'}
  - !powerShell:
    wait: true
    command: >-
      $modulesPath = """$([Environment]::GetFolderPath('Windows'))\AtlasModules""";

      function AddToVar($env, $value) {
            $a = [IO.Path]::PathSeparator;
            $b = [System.EnvironmentVariableTarget]::Machine;
            $c = [Environment]::GetEnvironmentVariables($b);

            [Environment]::SetEnvironmentVariable($env,
            ("""$($c.'Path');$value""" -replace ';',"""$a"""),
            $b);
      };

      AddToVar 'Path' """$modulesPath;$modulesPath\Apps;$modulesPath\Other;$modulesPath\Tools;$modulesPath\Scripts""";

  ################ NO LOCAL BUILD ################

  - !writeStatus: {status: 'Enabling DirectPlay'}
  - !run: {exe: 'DISM.exe', args: '/Online /Enable-Feature /FeatureName:"DirectPlay" /NoRestart /All', weight: 30}
  
  - !writeStatus: {status: 'Disabling Internet Explorer', builds: [ '<22000' ]}
  - !run: {exe: 'DISM.exe', args: '/Online /Disable-Feature /FeatureName:"Internet-Explorer-Optional-amd64" /NoRestart', weight: 30, builds: [ '<22000' ]}

  - !writeStatus: { status: 'Enabling development features' }
  - !run: {exe: 'DISM.exe', args: '/Online /Enable-Feature /FeatureName:"MicrosoftWindowsPowerShellV2Root" /NoRestart /All', weight: 30}
  - !run: {exe: 'DISM.exe', args: '/Online /Enable-Feature /FeatureName:"MicrosoftWindowsPowerShellV2" /NoRestart /All', weight: 30}
  - !run: {exe: 'DISM.exe', args: '/Online /Enable-Feature /FeatureName:"Microsoft-Hyper-V-All" /NoRestart /All', weight: 30}
  - !run: {exe: 'DISM.exe', args: '/Online /Enable-Feature /FeatureName:"Microsoft-Hyper-V" /NoRestart /All', weight: 30}
  - !run: {exe: 'DISM.exe', args: '/Online /Enable-Feature /FeatureName:"Microsoft-Hyper-V-Tools-All" /NoRestart /All', weight: 30}
  - !run: {exe: 'DISM.exe', args: '/Online /Enable-Feature /FeatureName:"Microsoft-Hyper-V-Management-PowerShell" /NoRestart /All', weight: 30}
  - !run: {exe: 'DISM.exe', args: '/Online /Enable-Feature /FeatureName:"Microsoft-Hyper-V-Hypervisor" /NoRestart /All', weight: 30}
  - !run: {exe: 'DISM.exe', args: '/Online /Enable-Feature /FeatureName:"Microsoft-Hyper-V-Services" /NoRestart /All', weight: 30}
  - !run: {exe: 'DISM.exe', args: '/Online /Enable-Feature /FeatureName:"Microsoft-Hyper-V-Management-Clients" /NoRestart /All', weight: 30}
  - !run: {exe: 'DISM.exe', args: '/Online /Enable-Feature /FeatureName:"HypervisorPlatform" /NoRestart /All', weight: 30}
  - !run: {exe: 'DISM.exe', args: '/Online /Enable-Feature /FeatureName:"VirtualMachinePlatform" /NoRestart /All', weight: 30}
  - !run: {exe: 'DISM.exe', args: '/Online /Enable-Feature /FeatureName:"Containers-DisposableClientVM" /NoRestart /All', weight: 30}
  - !run: {exe: 'DISM.exe', args: '/Online /Enable-Feature /FeatureName:"Containers" /NoRestart /All', weight: 30}
  - !run: {exe: 'DISM.exe', args: '/Online /Enable-Feature /FeatureName:"Containers-HNS" /NoRestart /All', weight: 30}
  - !run: {exe: 'DISM.exe', args: '/Online /Enable-Feature /FeatureName:"Containers-SDN" /NoRestart /All', weight: 30}
  - !run: {exe: 'DISM.exe', args: '/Online /Enable-Feature /FeatureName:"Microsoft-Windows-Subsystem-Linux" /NoRestart /All', weight: 30}

  ################ NO LOCAL BUILD ################

  - !writeStatus: {status: 'Disabling Steps Recorder'}
  - !run: {exe: 'DISM.exe', args: '/Online /Remove-Capability /CapabilityName:"App.StepsRecorder~~~~0.0.1.0" /NoRestart', weight: 30}

  - !writeStatus: {status: 'Disabling Legacy Media Player'}
  - !run: {exe: 'DISM.exe', args: '/Online /Disable-Feature /FeatureName:"WindowsMediaPlayer" /NoRestart', weight: 30}
  - !run: {exe: 'DISM.exe', args: '/Online /Remove-Capability /CapabilityName:"Media.WindowsMediaPlayer~~~~0.0.12.0" /NoRestart', weight: 30}

    # Initial software
    # 7-Zip, Visual C++ Runtimes, DirectX
  - !writeStatus: {status: 'Installing utilities'}
  - !powerShell:
    command: '.\SOFTWARE.ps1'
    exeDir: true
    wait: true
    weight: 150
    runas: currentUserElevated

    # Browsers
  - !writeStatus: {status: 'Installing Brave', option: 'browser-brave'}
  - !powerShell:
    command: '.\SOFTWARE.ps1 -Brave'
    exeDir: true
    wait: true
    weight: 120
    option: 'browser-brave'
    runas: currentUserElevated
  - !writeStatus: {status: 'Installing Firefox', option: 'browser-firefox'}
  - !powerShell:
    command: '.\SOFTWARE.ps1 -Firefox'
    exeDir: true
    wait: true
    weight: 120
    option: 'browser-firefox'
    runas: currentUserElevated
  - !writeStatus: {status: 'Installing LibreWolf', option: 'browser-librewolf'}
  - !powerShell:
    command: '.\LIBREWOLF.ps1'
    exeDir: true
    wait: true
    weight: 120
    option: 'browser-librewolf'
    runas: currentUserElevated
  - !writeStatus: {status: 'Installing Google Chrome', option: 'browser-chrome'}
  - !powerShell:
    command: '.\SOFTWARE.ps1 -Chrome'
    exeDir: true
    wait: true
    weight: 120
    option: 'browser-chrome'
    runas: currentUserElevated

  ################ END NO LOCAL BUILD ################
