---
title: Configure OEM Information
description: Configures OEM information to contain the Atlas version and the Atlas Discord server
actions:
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation'
    value: "Manufacturer"
    data: "Atlas"
    type: REG_SZ
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation'
    value: "Model"
    data: "AtlasOS v0.4.2986"
    type: REG_SZ
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation'
    value: "SupportURL"
    data: "https://github.com/hmerritt/win-atlas"
    type: REG_SZ
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation'
    value: "SupportPhone"
    data: "https://github.com/hmerritt/win-atlas"
    type: REG_SZ
  - !registryValue:
    path: 'HKLM\SOFTWARE\Atlas'
    value: "WinreFallbackFixed"
    data: "1"
    type: REG_SZ


